use inc::Module::JSAN::DSL;

name            JooseX.Namespace.Depended

version         0.01
author          'Nickolay (SamuraiJack) Platonov <root@symbie.org>'

abstract        'Dependencies handling implementation, integrated with Joose3'
license         bsd


requires        Joose                   3.005
requires        JooseX.SimpleRequest    0.01
requires        JooseX.Meta.Lazy        0.01


docs_markup     mmd